from tkinter import *

root = Tk()
root.title("Home Doctor")
root.geometry("600x600")

question1_ans = StringVar(value = 0)
question1_question = Label(root, text = "Do you have a headache?")
question1_question.pack()
question1_r1 = Radiobutton(root, text = "Yes", variable = question1_ans, value = "yes")
question1_r1.pack()
question1_r2 = Radiobutton(root, text = "No", variable = question1_ans, value = "no")
question1_r2.pack()

question2_ans = StringVar(value = 0)
question2_question = Label(root, text = "Do you have chest pain?")
question2_question.pack()
question2_r1 = Radiobutton(root, text = "Yes", variable = question2_ans, value = "yes")
question2_r1.pack()
question2_r2 = Radiobutton(root, text = "No", variable = question2_ans, value = "no")
question2_r2.pack()

question3_ans = StringVar(value = "0")
question3_question = Label(root, text = "Do you feel breathlessness?")
question3_question.pack()
question3_r1 = Radiobutton(root, text = "Yes", variable = question3_ans, value = "yes")
question3_r1.pack()
question3_r2 = Radiobutton(root, text = "No", variable = question3_ans, value = "no")
question3_r2.pack()

question4_ans = StringVar(value = "0")
question4_question = Label(root, text = "Do you feel breathlessness?")
question4_question.pack()
question4_r1 = Radiobutton(root, text = "Yes", variable = question3_ans, value = "yes")
question4_r1.pack()
question4_r2 = Radiobutton(root, text = "No", variable = question3_ans, value = "no")
question4_r2.pack()

question5_ans = StringVar(value = "0")
question5_question = Label(root, text = "Do you feel full after eating just a little?")
question5_question.pack()
question5_r1 = Radiobutton(root, text = "Yes", variable = question3_ans, value = "yes")
question5_r1.pack()
question5_r2 = Radiobutton(root, text = "No", variable = question3_ans, value = "no")
question5_r2.pack()

question6_ans = StringVar(value = "0")
question6_question = Label(root, text = "Do you have persistent or high fever?")
question6_question.pack()
question6_r1 = Radiobutton(root, text = "Yes", variable = question3_ans, value = "yes")
question6_r1.pack()
question6_r2 = Radiobutton(root, text = "No", variable = question3_ans, value = "no")
question6_r2.pack()

root.mainloop()